# Python para analisis de datos - Clase 3 (Laboratorios).ipynb

## Módulo 03 - Laboratorio 01

**Ejercicio 1**
Construir arrays a partir de una lista simple y una lista anidada usando tipos de datos numéricos distintos para cada una.

In [4]:
import numpy as np
b = np.array([[1,2,3,4],[5,6,7,8]])
lista=[1,3,5,6]
lista2=[5.0,6,8,9]
array_1D=np.array(lista)
array_2D=np.array([lista,lista2])
print("Array 1D:\n", array_1D)
print("Array 2D:\n",array_2D)

Array 1D:
 [1 3 5 6]
Array 2D:
 [[1. 3. 5. 6.]
 [5. 6. 8. 9.]]


In [8]:
array = np.array([[4,8,6],[2,3,5],[7,5,7]], dtype=np.float32)
array, array.dtype

(array([[4., 8., 6.],
        [2., 3., 5.],
        [7., 5., 7.]], dtype=float32),
 dtype('float32'))

**Ejercicio 2**
Construir una matriz de 4x5 a partir de:
1. listas anidadas y
2. números aleatorios

In [9]:
matriz_45=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
matriz_45, matriz_45.shape

(array([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]),
 (4, 5))

In [10]:
np.random.randint(0,100,(4,5))

array([[ 5, 16, 77, 26,  7],
       [52, 52, 47, 82, 92],
       [48, 93, 65, 12, 70],
       [12, 13, 60, 55, 80]])

**Ejercicio 3**
Construir un array lineal de 36 elementos. Cambiar el shape para que tenga:
1. 3 filas y 12 columnas
2. 4 columnas
3. dimensión 4

In [18]:
array36= np.array([n for n in range(0,36)])
array36, array36.shape
#3 filas y 12 columnas
array36.reshape(3,12)

#4 columnas
array36.reshape(9,4)

#dimensión 4
array36.reshape(2,2,3,3)
array36.reshape(2,2,3,3).ndim

4

**Ejercicio 4**
1. Dado un array de enteros de shape (4, 6) seleccionar:
<br>
a. El primer elemento de la primer fila<br>
b. La segunda fila<br>
c. La cuarta columna<br>
d. Las columnas de índice par<br>
e. Los elementos mayores a 7 (u otra condición a elección)<br>
2. Al mismo array asignarle el valor 100 al último elemento de la última fila.
3. Asignarle 0 a la quinta columna.

In [22]:
array46= np.random.randint(0,100,(4,6))
array46

array([[28, 35,  4, 21, 48, 70],
       [75, 68, 43, 49, 48, 13],
       [53, 23, 97, 69, 10,  2],
       [99, 63, 75, 90, 20, 64]])

In [25]:
#Primer elemento de la fila:
array46[0,0]

28

In [26]:
#La segunda fila
array46[1,:]

array([75, 68, 43, 49, 48, 13])

In [28]:
#La cuarta columna
array46[:,3]

array([21, 49, 69, 90])

In [31]:
#Las columnas de índice par
array46[:,::2]

array([[28,  4, 48],
       [75, 43, 48],
       [53, 97, 10],
       [99, 75, 20]])

In [32]:
#Los elementos mayores a 7 (u otra condición a elección)
array46[array46>7]

array([28, 35, 21, 48, 70, 75, 68, 43, 49, 48, 13, 53, 23, 97, 69, 10, 99,
       63, 75, 90, 20, 64])

In [37]:
#Al mismo array asignarle el valor 100 al último elemento de la última fila.
array46[3,5]=100  # Tambien podemos usar array46[-1,-1]
array46

array([[ 28,  35,   4,  21,  48,  70],
       [ 75,  68,  43,  49,  48,  13],
       [ 53,  23,  97,  69,  10,   2],
       [ 99,  63,  75,  90,  20, 100]])

In [39]:
#Asignarle 0 a la quinta columna.
array46[:,4]=0
array46

array([[ 28,  35,   4,  21,   0,  70],
       [ 75,  68,  43,  49,   0,  13],
       [ 53,  23,  97,  69,   0,   2],
       [ 99,  63,  75,  90,   0, 100]])

## Módulo 03 - Laboratorio 02

**Ejercicios**


1. Calcular los cubos de los primeros 15 naturales.


In [44]:
lista_numeros15= np.array([n for n in range(1,16)])
lista_numeros15

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

2. Sumar la matriz identidad a una matriz llena de unos.


In [54]:
matriz_unos= np.ones((4, 4), dtype=int)
print("Matriz de Unos \n", matriz_unos)
matriz_identidad= np.identity(4 , dtype=int)
print("Matriz identidad\n", matriz_identidad)
matriz_suma = matriz_identidad + matriz_unos
print("Matriz suma\n", matriz_suma)

Matriz de Unos 
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
Matriz identidad
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
Matriz suma
 [[2 1 1 1]
 [1 2 1 1]
 [1 1 2 1]
 [1 1 1 2]]


3. Hacer una función que calcule grados Fahrenheit a partir de un array con grados Celsius.


In [63]:
def celsius_to_fahrenheit(array_en_celsius):
    #ºF = (ºC · 1,8) + 32
    return (array_en_celsius*1.8 + 32)

#Ejemplo:

temperaturas= np.random.default_rng().uniform(0,50,10)
print("Temperaturas en Celsius: \n", temperaturas)

print("Temperaturas en Fahrenheit: \n", celsius_to_fahrenheit(temperaturas))

Temperaturas en Celsius: 
 [35.53476588 11.50326643  7.19696959  4.95316677 41.33246461 40.94722174
 49.63457491  2.82702351 33.83457231 23.03578732]
Temperaturas en Fahrenheit: 
 [ 95.96257858  52.70587957  44.95454527  40.91570019 106.3984363
 105.70499914 121.34223483  37.08864233  92.90223016  73.46441718]


4. Hacer una función que tome dos arrays (peso y altura) y calcule el índice de masa corporal.


In [65]:
def imc (peso, altura):
    return peso/altura/altura*100*100

peso=  np.random.default_rng().uniform(40,100,10)
altura=  np.random.default_rng().uniform(130,190,10)

print("Pesos: \n", peso)

print("Alturas: \n", altura)

print("IMC: \n", imc(peso, altura))

Pesos: 
 [58.46943706 71.839487   87.81991682 77.54002844 87.89307537 91.48379239
 63.70916195 79.87763629 71.39748824 60.4464169 ]
Alturas: 
 [158.15666838 145.49317894 178.025677   184.95614376 166.70070385
 170.05893752 139.96211738 145.66463118 137.18749831 140.05346958]
IMC: 
 [23.37512257 33.93735226 27.70943876 22.66670706 31.62858724 31.63335367
 32.5222725  37.64583876 37.93620299 30.81646493]


5. Crear una matriz de 4x5 llena de ceros. Sumar 10 a la tercera columna usando broadcasting.


In [71]:
matriz_ceros= np.zeros((4, 5),  dtype=int)
print("Matriz de CEROS \n", matriz_ceros)
matriz_ceros[:,2]=matriz_ceros[:,2] + 10
print("Matriz de CEROS \n", matriz_ceros)

Matriz de CEROS 
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Matriz de CEROS 
 [[ 0  0 10  0  0]
 [ 0  0 10  0  0]
 [ 0  0 10  0  0]
 [ 0  0 10  0  0]]


6. Encontrar los elementos de un array que son menores a los logaritmos al cuadrado de los elementos de otro array

In [78]:
array_inicial = np.random.randint(1,20,(10,10))
array_temporal = np.random.randint(1,20,(10,10))
print("El array inicial es \n", array_inicial)
print("El array de calculo comparativo  es \n", array_temporal)


array_resultado= array_inicial[array_inicial< np.log(array_temporal)**2]
print("\nLos elementos de un array que son menores a los logaritmos al cuadrado de los elementos son: \n", array_resultado)

El array inicial es 
 [[12  4  4 19 17  4 11  7  1  4]
 [ 9  3 11 10 14 19 15  1  5 13]
 [17  1 12  5  4 15  4  9  6  7]
 [ 5  9 12  8 19 19 11  9 10  2]
 [14 14  6 11 19 15 18  9 13 19]
 [18  6 10 14  8  2 10  4  1  2]
 [ 8  6  9  4  3 15 19 19 12  7]
 [ 3  6 18  9  2  5 10 10  8 19]
 [14 11  1 12  4  5  4 10  1 17]
 [19 14 13 15 15 11  3 12  6 12]]
El array de calculo comparativo  es 
 [[17 12  3  6 11 10 17  6 15  2]
 [17  1 13 17  5  4  6 10  5  3]
 [14 16  8 12 19  3 16 14  7  8]
 [10 16 13  4 12 19  3 14 10 16]
 [11  8  7 11  7  4 12  5 17  2]
 [17 19  9 17 17  8 17  6  9 12]
 [ 5  6  4 14  7 12 19 15  7  7]
 [ 5  9 19 17  6 14  6  8  6 18]
 [ 6 17 18 11  2  3  5  9 10 14]
 [18  9 17 16 19  5  9 19 11 10]]

Los elementos de un array que son menores a los logaritmos al cuadrado de los elementos son: 
 [4 4 1 1 1 5 4 4 5 2 6 8 2 1 2 4 3 2 5 1 1 3]


## Módulo 03 - Laboratorio 03

**Ejercicios**
1. Crear un array a partir del archivo “numeros.csv”
2. ¿Cuántas filas y columnas tiene?
3. Realizar las siguientes estadísticas para todas las columnas: promedio, desviación standard, mínimo y máximo
4. ¿Qué columna tiene mayor dispersión?
5. ¿Qué columna abarca un rango de números más amplio?

In [82]:
#Crear un array a partir del archivo “numeros.csv”
from numpy import genfromtxt
data = genfromtxt('../Recursos/numeros.csv', delimiter=' ', skip_header = 0)
print(data)

[[ 4.813  3.892 15.295 14.966 -2.629 10.321]
 [ 6.281  1.71  15.081 11.82  -5.391  9.507]
 [ 5.923  4.602 14.809  8.604 -2.694  9.48 ]
 ...
 [ 4.408  2.114 15.326  8.805 -3.355 11.287]
 [ 6.437  2.542 15.378 13.038 -4.922 11.014]
 [ 6.665  0.87  15.143 17.716 -3.466  8.881]]


In [99]:
# ¿Cuántas filas y columnas tiene?
print("Filas:", data.shape[0])
print("Columnas:", data.shape[1])

Filas: 50000
Columnas: 6


In [100]:
# Realizar las siguientes estadísticas para todas las columnas: promedio, desviación standard, mínimo y máximo
print("La suma de todos lo elementos es: \n" , data.sum() )
print("La suma de todos lo elementos de cada columna es: \n" , data.sum(axis=0) )
print("El promedio detodos lo elementos de cada columna es: \n" , data.mean(axis=0) )
print("El desvio estandard detodos lo elementos de cada columna es: \n" , data.std(axis=0) )
print("El minimo de todos lo elementos de cada columna es: \n" , data.min(axis=0) )
print("El maximo de todos lo elementos de cada columna es: \n" , data.max(axis=0) )


La suma de todos lo elementos es: 
 2101382.556
La suma de todos lo elementos de cada columna es: 
 [ 299987.07   100346.057  750127.715  601532.993 -150395.556  499784.277]
El promedio detodos lo elementos de cada columna es: 
 [ 5.9997414   2.00692114 15.0025543  12.03065986 -3.00791112  9.99568554]
El desvio estandard detodos lo elementos de cada columna es: 
 [1.00023883 2.00229762 0.4993279  3.00265157 2.496453   1.50167353]
El minimo de todos lo elementos de cada columna es: 
 [  1.639  -6.068  12.767   0.015 -13.386   4.398]
El maximo de todos lo elementos de cada columna es: 
 [10.409 11.162 17.09  23.678  7.668 16.516]


In [93]:
# ¿Qué columna tiene mayor dispersión?
print("La columna con mayor dispersion es : \n" , np.argmax(data.std(axis=0)) )

La columna con mayor dispersion es : 
 3


In [98]:
#  ¿Qué columna abarca un rango de números más amplio?
print("La diferencia entre el valor maximo y minimo de cada columna es: \n" , data.max(axis=0) - data.min(axis=0)  )
print("La columna que abarca un rango de numeros mas amplio  es: \n" ,np.argmax(data.max(axis=0) - data.min(axis=0) ))

La diferencia entre el valor maximo y minimo de cada columna es: 
 [ 8.77  17.23   4.323 23.663 21.054 12.118]
La columna que abarca un rango de numeros mas amplio  es: 
 3


## Módulo 03 - Laboratorio 04

**Ejercicios**
1. Crear un vector de diez números al azar.
2. Calcular la norma del vector usando:
<ul>
a. producto escalar.<br>
b. función a tal efecto.
</ul>
3. Crear una matriz de 2x3 y multiplicarla por su traspuesta.
4. Multiplicar la matriz identidad por un vector columna.

In [102]:
# Crear un vector de diez números al azar.
vector= np.random.randn(10)
print(vector)

[ 1.05809655 -0.05859757  2.96227287 -0.63014122 -0.0131815   0.19330076
  0.76834703 -0.02649708  0.21181833  0.06937685]


In [104]:
# Calcular la norma del vector usando:

    #a. producto escalar.
print("El producto escalar es(Calculado con dot): ", np.sqrt(vector.dot(vector)))
    #b. función a tal efecto.
print("El producto escalar es(Calculado con linalg.norm ) : ",    np.linalg.norm(vector))

El producto escalar es(Calculado con dot):  3.3126151087302738
El producto escalar es(Calculado con linalg) :  3.3126151087302738


In [109]:
# Crear una matriz de 2x3 y multiplicarla por su traspuesta.
matriz= np.random.randint(0,9,(2,3))
print("La matriz de 2x3 es: \n", matriz)
print("La matriz transpuesta es: \n", matriz.T)
print("El producto vectorial con su transpuesta es: \n", matriz.dot(matriz.T))

La matriz es: 
 [[7 4 3]
 [1 1 1]]
La matriz transpuesta es: 
 [[7 1]
 [4 1]
 [3 1]]
El producto vectorial con su transpuesta es: 
 [[74 14]
 [14  3]]


In [110]:
# Multiplicar la matriz identidad por un vector columna.
I = np.identity(10)
vector_columna = np.random.randint(0,9,(10,1))
print("Matriz identidad: n", I)
print("Vector columna: \n", vector_columna)
print("Producto de la matriz identidad por el vector columna: \n", I.dot(vector_columna))

Matriz identidad: n [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
Vector columna: 
 [[3]
 [2]
 [0]
 [7]
 [0]
 [1]
 [2]
 [0]
 [5]
 [7]]
Producto de la matriz identidad por el vector columna: 
 [[3.]
 [2.]
 [0.]
 [7.]
 [0.]
 [1.]
 [2.]
 [0.]
 [5.]
 [7.]]
